### ISSUE TITLE
This is a great idea, dynamic queries

### ISSUE THREAD

**Issue by papyr** [xafero/Coaster#1]
Hello this is a great idea, would be great if we could dynamic queries based on the attributes of an expando object.

Let me explain, we get new undefined JSON structures over the wire, and we have to query them. I can easily serialize them but querying them on their member attributes is a challenge, any way you can help us get the member attributes and types into a query filter would greatly help..

For our use case, when we have the class metadata, a) we display the  C# metadata attributes as a filter and names which allows the user to select the attributes as filters and filter the data, b) `is there a way to construct the query based on the attributes coming back from the expando/C# class`

![image](https://github.com/xafero/Coaster/assets/12733414/0b898ab8-d3c6-42f7-aa49-d6d45ac768da)

**Comment by xafero** [comment]
So dynamic Func<T> delegate or IFunc interface implementation... possible.

Can you provide me more details on xafero . dev at hotmail . com ?

**Comment by xafero** [comment]
![image](https://github.com/xafero/Coaster/assets/6005006/6a869ac4-7e7b-4955-89f1-2093dcf02df8)

**Comment by xafero** [comment]
Are you there?

**Comment by xafero** [comment]
Closed due to non-responsiveness.

**Comment by papyr** [comment]
can you please add a sample
